### ISSUE TITLE
error alert displayed

### ISSUE THREAD

**Issue by stevefaulkner** [ThePacielloGroup/aviewer#15] opened 2016-02-13 11:43 UTC
<img width="945" alt="capture" src="https://cloud.githubusercontent.com/assets/835859/13027403/daf3d786-d246-11e5-8eea-98a0416d77ec.PNG">
occurs on http://oaa-accessibility.org/rulesets/ page using dev branch 32bit aviewer with laltest Firefox on windows 10

**Comment by patrickhlauke** [comment] 2016-09-05 16:05
seems fixed / cannot reproduce

**Comment by patrickhlauke** [comment] 2016-09-05 16:06
actually, ignore me...i've tested with 64bit aViewer, not 32bit aViewer

**Comment by patrickhlauke** [comment] 2017-03-31 12:32
@stevefaulkner could you try the latest version https://github.com/ThePacielloGroup/aviewer/releases/tag/2.0.1.0 and report back if it's still an issue?

**Comment by patrickhlauke** [comment] 2017-03-31 14:48
cannot reproduce anymore myself with latest version (forcing it to use 32bit, nor in the 64bit version). closing for now, but feel free to reopen if you do still see issues...

**Closed as completed by patrickhlauke** 2017-03-31 14:48 UTC
Labels: bug
